---
- hosts: all
  become: true
  tasks:
  - name: install apache http servers
    yum:
      name: httpd
      state: latest
  - name: start httpd start...
    service:
      name: httpd
      state: started
      enabled: true
